build-and-push:
    stage: build
    tags:
        - docker
        - omega
    only:
        - main
    image: docker-repository.intern.neusta.de/tn-buildx
    variables:
        IMAGE_NAME: "teamneusta/remote-php-kata"
        IMAGE_TAG: "8.3"
        DOCKER_BUILDKIT: 1
        DOCKER_DRIVER: overlay2
        BUILDER_NAME: multiarch-$CI_JOB_ID
    before_script:
        - docker version
        - docker buildx create --name "${BUILDER_NAME}" --driver docker-container --driver-opt image=docker-repository.intern.neusta.de/tn-buildkit --use
        - docker buildx inspect --bootstrap
        - update-binfmts --enable
        - cat "${DOCKERHUB_ACCESS_TOKEN}" | docker login --username "${DOCKERHUB_USER}" --password-stdin
    after_script:
        - docker buildx rm "${BUILDER_NAME}"
    script:
        - sh ./build.sh
