version: '3.4'
services:
  php:
    image: "docker-repository.intern.neusta.de/php/kata:8.1"
    build:
      context: .
      args:
        docker_registry: ${KATA_DOCKER_REGISTRY:-docker-repository.intern.neusta.de}
    volumes:
    - ./:/app
    environment:
      XDEBUG_MODE: debug
    expose:
      - 9003 # xdebug 3 port!
