services:
  php:
    image: "${KATA_DOCKER_REGISTRY:-docker-repository.intern.neusta.de}/teamneusta/remote-php-kata:8.3"
    volumes:
    - ./:/app
    environment:
      XDEBUG_MODE: debug
    expose:
      - 9003 # xdebug 3 port!
